// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7m9tPIm5py66zLkwXfhR8nGlIwzLMF1k',
    appId: '1:679108484170:web:91748f92ea6e5111399ab3',
    messagingSenderId: '679108484170',
    projectId: 'spotify-app-1b702',
    authDomain: 'spotify-app-1b702.firebaseapp.com',
    storageBucket: 'spotify-app-1b702.firebasestorage.app',
    measurementId: 'G-1PLV2LCS86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCavE43qdipjqghruL_d5vuVPgrkhIzmNQ',
    appId: '1:679108484170:android:aca24320bddeac2f399ab3',
    messagingSenderId: '679108484170',
    projectId: 'spotify-app-1b702',
    storageBucket: 'spotify-app-1b702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhcHL6baHjJ-YyG5qywbKu1dwWGhpzGNQ',
    appId: '1:679108484170:ios:831b3ac5ba78a8d1399ab3',
    messagingSenderId: '679108484170',
    projectId: 'spotify-app-1b702',
    storageBucket: 'spotify-app-1b702.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhcHL6baHjJ-YyG5qywbKu1dwWGhpzGNQ',
    appId: '1:679108484170:ios:831b3ac5ba78a8d1399ab3',
    messagingSenderId: '679108484170',
    projectId: 'spotify-app-1b702',
    storageBucket: 'spotify-app-1b702.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7m9tPIm5py66zLkwXfhR8nGlIwzLMF1k',
    appId: '1:679108484170:web:e15603702a673e1b399ab3',
    messagingSenderId: '679108484170',
    projectId: 'spotify-app-1b702',
    authDomain: 'spotify-app-1b702.firebaseapp.com',
    storageBucket: 'spotify-app-1b702.firebasestorage.app',
    measurementId: 'G-3WKK995J5P',
  );
}
